version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kallani_app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8000:8000"
    networks:
      - media_backend

networks:
  media_backend:
    external: true
